version: '0.1'

services:

  mongo:
      image: mongo
      container_name: otterstore-mongo
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db
      environment:
        - MONGO_INITDB_DATABASE=OtterStore
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=example
        
  app-api:
    build: ./AppsAPI
    container_name: otterstore-app-api
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  checkout-api:
    build: ./CheckOutAPI
    container_name: otterstore-checkout-api
    ports:
      - "5002:5002"
    depends_on:
      - mongo

  cors-proxy:
    build: ./CORSProxy
    container_name: otterstore-CORS-proxy
    ports:
      - "3000:3000"

  flutter-web-app:
    build: ./otterstore_frontend
    container_name: otterstore-flutter-web-app
    ports:
      - "80:80"

volumes:
  mongo-data:
