# docker-compose up --scale checkout-api=3 -d
version: '0.1'
networks:
  otterstore:
    driver: bridge

services:
  mongo:
      image: mongo
      container_name: otterstore-mongo
      ports:
        - "27017"
      volumes:
        - mongo-data:/data/db
      environment:
        - MONGO_INITDB_DATABASE=OtterStore
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=example
        
  app-api:
    build: ./AppsAPI
    ports:
      - "5001"
    networks:
      - otterstore
    depends_on:
      - mongo

  checkout-api:
    build: ./CheckOutAPI
    ports:
      - "5002"
    networks:
      - otterstore
    depends_on:
      - mongo

  cors-proxy:
    build: ./CORSProxy
    container_name: otterstore-CORS-proxy
    ports:
      - "3000:3000"
    networks:
      - otterstore

  flutter-web-app:
    build: ./otterstore_frontend
    container_name: otterstore-flutter-web-app
    ports:
      - "80:80"
    networks:
      - otterstore

volumes:
  mongo-data:
